### ISSUE TITLE
Implementation of embeds.

### ISSUE THREAD

**Issue by svr333** [discord-bot-tutorial/Miunie#104]
I've been wondering about this for a bit now.

Embeds are currently not being used in any command (with exception to the help command), and I personally think it would be a good idea to implement embeds, since they allow us to bring more information in an eleganter and more user-friendly way.

Is there a reason why we haven't implemented this yet? Are we never going to implement it?
Do you think it's a good idea to implement it?

Have a good day :)

**Comment by Charly6596** [comment]
We talked about embeds in Miunie a while ago, and if i remember correctly, in that conversation we talked about to not have nothing related to embeds in the Core, Core would have a `RequestModel` and a `ResponseModel`, so whenever you need data from a command, you create a `RequestModel`, send it to a Core service, which returns a `ResponseModel`. That response model would have information about the representation, information Miunie.Discord can understand to turn it into a proper view.
In that conversation, there was also another option, to have interfaces with methods such as `SendMessageAsync`, `SendEmbedAsync`, and stuff like that, which seems what we're currently doing.

So to answer your questions: 
- We've talked about embeds before and no one said no to embeds yet (as far as i know)
- The reason i can think about is simplicity, we had to focus more on developing Core functionalities, otherwise we wouldn't have anything to represent with embeds.
- And yes, in my opinion would be nice to have embeds (: following the `MiunieUser`, `MiunieRole` 
and other discord related entities/providers/services implementation, we could also have a `MiunieEmbed` and a `SendEmbed` method

Let's see what others think about that :thinking:

**Comment by petrspelos** [comment]
Was discussed on yesterday's LiveShare session, it's not using a dedicated ResponseModel, implementation is already designed.

There will be a proper issue for it soon.
Closing
