### ISSUE TITLE
Implement logger with history

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#124]
Current implementation of logging only delegates into an output device (be it console or nothing at all in UWP).

A better implementation of a logger is desirable. One that keeps the log in memory (or optionally in a file).

--------

> ℹ This will be done through LiveShare

**Comment by Emzi0767** [comment]
Have you considered using [Microsoft Logging Abstrations](https://www.nuget.org/packages/Microsoft.Extensions.Logging) instead of homebrew logging implementation? Seems like it would make logging in the bot easier and more flexible (not to mention the added benefit of being able to easily plug in all sorts of 3rd party loggers).
