### ISSUE TITLE
Implement reputation (part of the profile commands) functionality.

### ISSUE THREAD

**Issue by svr333** [discord-bot-tutorial/Miunie#68]
This add-on to the ProfileService would create the ability to get and update the amount of reputation on said user. There would also be a command to give said user 1 reputation every x period. And a command that only retrieves someone's reputation amount.

**For example:**
_In the ProfileService.cs:_
public (u)int GetReputation(MiunieUser m, MiunieChannel c) { }
public (u)int AddReputation(MiunieUser m, (u)int amount) {}
Optional: RemoveReputation(MiunieUser m, MiunieChannel c, (u)int amount)

_In the Modules:_
Command group reputation with following commands:
**[Command("")]** => Get user reputation of mentioned user or command executioner.
**[Command("add")]** => Give one reputation to mentioned user. Cannot give to self.
Optional: **[Command("remove")]** => Remove x reputation of mentioned user or self.

These commands would basically call ProfileService and then send a confirmation message to the channel.

Open for expansion/changes.

**************
EDIT:

Peter and I agreed, on voice chat, that we will make the system as follows:

Every user gets 1 plusRep and 1 minusRep over x time. The time will be a constant for now, we can always  refactor it into a configuration file.

**Comment by DraxCodes** [comment]
To clarify, with a command group setup. The expected behaviour would be:
```Elm
@bot rep => "Returns Users rep"
@bot rep add x => "Add's "x" rep to the user"
@bot rep remove x => "Removes "x" rep from the user"
```

While I feel this is a solid route to take, I also think it's sorta not needed. My thinking is as follows.
`@bot rep => Returns Users rep`, seems redudant, we already have this setup via the `profile` command. 
The Add & Remove commands also seem to have no real function. Is there a reason for having them? Possibly Staff can give rep based on user acomplishments? (idk about that idea)

In my opinion the rep system should all be background with the only output being from the profile command.

**Comment by svr333** [comment]
I'm aware that's how a command group behaves, I've used it myself before and I find it useful.

Okay, then the separate _@bot rep_ command can be left out. And, how I had the reputation system in mind was that, every user gets 1 rep to spend to 1 user every day or maybe even 12 hours. It's a pretty balanced system, and other bots use it likewise.

The reason why we may have the rep remove one is so that, for instance, someone behaved badly or someone got kicked/banned, that an admin or someone with said permissions can totally reset or remove some of his/her reputation.
